// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chnrurahkyiuolrsxlgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNobnJ1cmFoa3lpdW9scnN4bGdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NDQwMTAsImV4cCI6MjA1ODUyMDAxMH0.KjDYtOR3QKOBNLh-aNVME8ok0w07350qQOJThiT2aCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);